name: timework
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  shamsi_date: ^1.0.1
  jalali_flutter_datepicker: ^1.0.1
  flutter:
    sdk: flutter
  floor: ^1.4.2
  floor_generator: ^1.4.2
  sqflite: ^2.3.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: IRANSans
      fonts:
        - asset: assets/fonts/IRANSans(FaNum).ttf
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48